WitchFreya/SWSAddons

addons/vehicles/CfgVehicles.inc, addons/vehicles/CfgVehicles/Viper.inc
- Fixes issue where multiple sensor targets caused the commander turret to behave irregularly
- Fixes issue where gunner cannot select laser targets provided by other units
=> Fix: viper targeting and turret tweaks

addons/patches/optre_weapons_gl/CfgWeapons.inc, addons/patches/optre_weapons_gl/config.cpp, addons/patches/optre_weapons_gl/script_component.hpp, addons/weapons/ar0m37s/CfgWeapons.inc, addons/weapons/flares/CfgMagazineWells.inc, addons/weapons/m3sx/CfgMagazineWells.inc, addons/weapons/m9sx/CfgMagazineWells.inc, addons/weapons/ma5bsx/CfgWeapons.inc
This also makes some refactors with CBA magwells and appending to our stuff.
=> fix(#58): Allow sidearm GL to use 3rnds

addons/patches/dev_flood_combat/CfgVehicles.inc, addons/patches/dev_flood_combat/config.cpp
=> fix(dev_flood_combat): Missing XEH for Precursor Spartan

addons/patches/retirement/CfgVehicles.inc, addons/patches/retirement/README.md, addons/patches/retirement/config.cpp, addons/patches/retirement/script_component.hpp
=> fix(retirement): Patch sound config warning from dropbays

addons/vehicles/CfgEventHandlers.inc, addons/vehicles/XEH_PREP.inc.sqf, addons/vehicles/XEH_postInit.sqf, addons/vehicles/XEH_preInit.sqf, addons/vehicles/XEH_preStart.sqf, addons/vehicles/config.cpp, addons/vehicles/functions/fnc_scanGroundVehicles.sqf, addons/vehicles/functions/script_component.inc.sqf
- Based on the work by @EmilyWinjum.
- Closes #83
=> feat(vehicles): Add SWS vics to Pelican drop

addons/logic/CfgEventHandlers.inc
Function invocations are hard.
=> fix(logic): AllowDamage should now transfer locality properly

addons/patches/opaex_functions/CfgEventHandlers.inc, addons/patches/opaex_functions/XEH_preClientInit.sqf, addons/patches/opaex_functions/XEH_preInit.sqf, addons/patches/opaex_functions/config.cpp, addons/patches/opaex_functions/initSettings.inc.sqf, addons/patches/opaex_functions/script_component.hpp
- Stop the EH for arsenalOpen that shows the MJOLNIR message.
=> fix(patches/opaex_functions): Stop spamming the OPAEX MJOLNIR message

addons/patches/optre_weapons_fg75/CfgVehicles.inc, addons/patches/optre_weapons_fg75/CfgWeapons.inc, addons/patches/optre_weapons_fg75/config.cpp, addons/patches/optre_weapons_fg75/script_component.hpp, addons/statics/config.cpp, addons/statics/optre/CfgVehicles.inc, addons/statics/optre/config.cpp
- Default to the AP rounds so that AI will actually use them.
- Add a BLUFOR version of the FG75
=> feat(statics): BLUFOR FG75 and fixes for ace/ai

addons/weapons/XEH_preInit.sqf
Self-explanatory. 1->2 meters.
=> fix(weapons): Increase distance before C7-Sx sticks

addons/air/heli_songbird/CfgVehicles.inc, addons/air/heli_songbird/config.cpp
Manually redefined all the turrets so they'd work even though they were still visibly correctly inherited in the config.
=> fix (songbird): Magpie bench seats not working

addons/medical/ACE_Medical_Treatment.inc
- Medigel now treats all minor injuries. Moderate and major injuries must be addressed by QuikClots or a medic.
- Medigel will treat Moderate and Major injuries for Abrasions, Contusions, Thermal Burns, and Crushing injuries.
N/A
=> feat(medical): Medigel affects additional injury types.

addons/patches/41st/CfgVehicles.inc, addons/patches/41st/config.cpp
Fix the Stomper RCWS to allow it to fire once more.
=> fix(41): Allow stomper RCWS to work again

addons/units/o_cla/faction.inc
Replaced several 3rnd GL magazines to 1rnd magazines, as well as small inventory tweaks.
Looked through units armed with underbarrel GLs and replaced 3rnd magazines with 1rnd magazines. Removed some other smokes and items that were unnecessary.
=> Updated faction.inc

addons/aceax/41st_compat/XtdGearInfos.inc, addons/aceax/41st_compat/XtdGearModels.inc, addons/aceax/41st_compat/config.cpp, addons/aceax/41st_compat/script_component.hpp, addons/aceax/opcan_compat/XtdGearInfos.inc, addons/aceax/opcan_compat/XtdGearModels.inc, addons/aceax/opcan_compat/config.cpp, addons/aceax/opcan_compat/script_component.hpp
Adds a handful of OPCAN helmets and 41st vests into ACEAX categories.
=> feat(aceax): Compats for OPCAN and 41st

addons/units/o_cla/CfgVehicles.inc, addons/units/o_cla/config.cpp, addons/vehicles/viper/CfgVehicles.inc, addons/vehicles/viper/config.cpp
The CLA require Lambs, so I made the CLA an optional addon.
=> feat: Make LAMBS_Danger optional in our modpack

addons/patches/pollution/CfgVehicles.inc
Correct the error message that popped up about turret not being a value.
=> fix(pollution): Correct the turret error message

addons/arsenal/CfgVehicles.inc, addons/arsenal/XEH_PREP.inc.sqf, addons/arsenal/XEH_preStart.sqf, addons/arsenal/config.cpp, addons/arsenal/functions/fnc_addFullArsenal.sqf, addons/arsenal/functions/fnc_attributeAddDefaults.sqf, addons/arsenal/functions/fnc_moduleAddFullArsenal.sqf, addons/common/CfgFactionClasses.inc, addons/common/CfgVehicles.inc, addons/common/config.cpp
- Add a Zeus module for creating an SWS Arsenal
- For some reason it doesn't work in singleplayer Zeus.
- Improve the whitelist/blacklist behavior in 3DEN; now it will factor in anything you may have already blacklisted/whitelisted before adding the other SWS items.
=> feat(arsenal): Add Zeus module and whitelist behavior improvement

addons/vehicle_trenches/$PBOPREFIX$
Fix an error about vehicle_trenches not being available.
=> fix(vehicle_trenches): unbroke a name

addons/patches/optre_jsrs_compat/CfgWeapons.inc, addons/patches/optre_jsrs_compat/config.cpp, addons/patches/optre_jsrs_compat/script_component.hpp
The OPTRE JSRS Compat mod incorrectly defines the inheritance of the M319N, which was hiding it from the virtual arsenal. This restores it.
=> fix(optre): Add the M319N GL back to the arsenal

.hemtt/project.toml, .vscode/tasks.template-hemtt-local.json
@EidolonForgery you can launch in VR now by doing `hemtt launch default vr_black` or `hemtt launch full vr_black`.
=> build(hemtt): Clean up the configs to leverage the new hemtt options

addons/optre_compat/config.cpp
- Corrects the addon name for `optre_compat`.
=> fix(optre_compat): Correct the addon name

addons/acre/$PBOPREFIX$, addons/acre/CfgWeapons.inc, addons/acre/README.md, addons/acre/config.cpp, addons/acre/script_component.hpp, addons/acre/unsc_foundries_compat/CfgVehicles.inc, addons/acre/unsc_foundries_compat/config.cpp, addons/acre/unsc_foundries_compat/script_component.hpp
- Makes UNSC Foundries compatible with ACRE
- Puts the ACRE items into the Tools section of ACE Arsenal instead of Misc.
- Note that saving/restoring radios like TFAR doesn't work with this by default.
=> feat(acre): ACRE compatibility

addons/optre_compat/CfgGlasses.inc, addons/optre_compat/config.cpp, addons/optre_compat/jsrs/config.cpp, addons/optre_compat/script_component.hpp, addons/tech/cbrn_protection/CfgGlasses.inc, addons/tech/cbrn_protection/config.cpp, addons/tech/cbrn_protection/script_component.hpp, docs/ACEInteractions.md, docs/ace.md
- Adds our own version of the CBRN Module from OPTRE to the arsenal.
- When ACE SpO2 is enabled, this will function as an oxygen supply as well.
- Additionally, ensures that the OPTRE CBRN base and this item stays on the face when swimming.
- Addresses #206.
=> feat(tech): Add CBRN attachment to facewear

addons/arsenal/XEH_preStart.sqf, addons/optre_compat/CfgWeapons.inc
- There are some bugs with the attachments fixes for OPTRE rn that I'll have to correct for later. **Does not fix** #188. Reverts the changes from the previous attempt at fixing.
=> fix(optre_compat): Remove attachments overrides for now

addons/optre_compat/config.cpp, addons/optre_compat/ui/RscAttributes.inc, addons/unsc_foundries_compat/$PBOPREFIX$, addons/unsc_foundries_compat/config.cpp, addons/unsc_foundries_compat/script_component.hpp, addons/unsc_foundries_compat/ui/RscAttributes.inc
=> fix: widthRailWay missing for drop pad maps

addons/common/XEH_PREP.inc.sqf, addons/common/fnc_isInVehicle.sqf, addons/wmo/$PBOPREFIX$, addons/wmo/CfgEventHandlers.inc, addons/wmo/CfgFunctions.inc, addons/wmo/README.md, addons/wmo/XEH_PREP.inc.sqf, addons/wmo/XEH_postInit.sqf, addons/wmo/XEH_preInit.sqf, addons/wmo/XEH_preStart.sqf, addons/wmo/config.cpp, addons/wmo/functions/fnc_setPosi.sqf, addons/wmo/functions/script_component.inc.sqf, addons/wmo/script_component.hpp
- Fix draining player stamina when standing on top of a moving object
- Fix a potential issue with rappelling.
- Sets up a location for a potential rewrite of WMO at some point.
=> fix(wmo): Avoid draining stamina when walking on moving objects

addons/aceax/config.cpp, addons/acre/config.cpp, addons/aed/config.cpp, addons/air/config.cpp, addons/arsenal/config.cpp, addons/cbrn_scripts/config.cpp, addons/common/config.cpp, addons/fortify/config.cpp, addons/gear/config.cpp, addons/logic/config.cpp, addons/main/config.cpp, addons/medical/config.cpp, addons/modules/config.cpp, addons/optre_compat/config.cpp, addons/patches/config.cpp, addons/resupply/config.cpp, addons/statics/config.cpp, addons/tech/config.cpp, addons/tfar/config.cpp, addons/things/config.cpp, addons/ui/config.cpp, addons/units/config.cpp, addons/unsc_foundries_compat/config.cpp, addons/vehicles/config.cpp, addons/weapons/config.cpp, addons/zeus/config.cpp
This applies to spots like the in-game addon dependencies menu in 3DEN.
=> refactor: Use COMPONENT_NAME so names are pretty where relevant

addons/wmo/$PBOPREFIX$
=> fix(wmo): Correct the PBO path

.hemtt/project.toml, addons/acre/XEH_preInit.sqf, addons/acre/XEH_preStart.sqf, addons/acre/config.cpp, addons/acre/script_component.hpp, addons/acre/ui/RscAttributes.inc, addons/acre/ui/RscCommon.inc, addons/acre/unsc_foundries_compat/config.cpp
- Hovering over the ACE Communications button will show a tooltip indicating where to find ACRE radio stuff.
- ACRE radios are categorized on the right—all of them will appear in tools, as will the Ground Spike Antenna + variants, then the just the radios will appear in a custom button on the right.
=> feat(acre): Minor QoL improvements

addons/acre/unsc_foundries_compat/config.cpp
I don't know why this works sometimes and doesn't others. Whatever.
=> fix(acre): Correct circular dependency

addons/acre/CfgEventHandlers.inc, addons/acre/CfgWeapons.inc, addons/acre/XEH_PREP.inc.sqf, addons/acre/XEH_postClientInit.sqf, addons/acre/XEH_preClientInit.sqf, addons/acre/XEH_preClientStart.sqf, addons/acre/XEH_preInit.sqf, addons/acre/XEH_preStart.sqf, addons/acre/functions/fnc_radioClassNames.sqf, addons/acre/functions/script_component.inc.sqf, addons/acre/gear_adjustment/CfgWeapons.inc, addons/acre/gear_adjustment/README.md, addons/acre/gear_adjustment/config.cpp, addons/acre/gear_adjustment/script_component.hpp, include/z/ace/addons/arsenal/defines.hpp
- When ACRE is loaded, our vests will have an additional 5lbs of carry capacity to accommodate for other radios.
- Unique ACRE radios will appear in the custom Arsenal right panel properly.
=> feat(acre): QoL and carry capacity adjustments

addons/weapons/howdy/script_component.hpp
Does what it says on the tin. Howdy heavy now.
=> feat(weapons): Increase Howdy unloaded weight from 3lbs to 10lbs

addons/air/heli_songbird/CfgWeapons.inc, addons/air/heli_songbird/config.cpp, addons/air/optre_vehicles_hornet/CfgWeapons.inc, addons/air/optre_vehicles_hornet/config.cpp
=> fix: Correct the inheritance on Songbird and Hornet guns

addons/optre_compat/CfgWeapons.inc
- Correctly handle the inheritance and definition of OPTRE lasers to avoid them greying out loadouts constantly.
=> fix(optre_compat): Correct the attachments greying out loadouts

addons/patches/v_fz_air_vehicles/CfgVehicles.inc, addons/patches/v_fz_air_vehicles/config.cpp, addons/patches/v_fz_air_vehicles/script_component.hpp
Just fixed the fact that they have a normal soldier in the crew instead of a UAV AI.
=> fix(v_fz_air_vehicles): Wombats no longer automatically take off nor eject pilots

addons/air/uav_smq94/CfgVehicles.inc, addons/air/uav_smq94/config.cpp
- Bumped maxRange from 500 to 1k, limited by View Distance.
- Enabled recognizing specific types out to 750m.
=> feat(air): Increase range on SMQ-94 ManSensor

addons/units/o_ura/CfgVehicles.inc
- Replaced the vests on the non-marine units.
- As a result of the replacement vests having less space, the following units have one less magazine than before for their launchers:
- `SWS_O_URArmy_Anti_Air_Person_01`
- `SWS_O_URArmy_Anti_Tank_Person_01_01`
- `SWS_O_URArmy_Anti_Air_Person_01`
=> feat(units/o_ura): Replace vests on non-marine units

addons/tech/optic_sxmr10/CfgWeapons.inc, addons/tech/optic_sxmr10/config.cpp
=> fix(tech/optic_sxmr10): Restore iron sights

addons/medical/CfgWeapons.inc, addons/medical/config.cpp
Reduce OPTRE Medical Kit to weigh the same as Personal Aid Kit.
=> Reduce medkit weight

addons/units/o_ura/CfgVehicles.inc
Correct the missing seats on the Dagger and Jeep for the URA.
=> fix(units/o_ura): Vehicles missing seats

addons/units/o_ura/CfgVehicles.inc
- Adjustments to ammo and armor of Sniper & AR unit.
- Adjustments to munitions of AT 02.
- Added unarmed Jeep variant.
=> feat(units/o_ura): Minor adjustments and new Jeep vehicle

addons/patches/optrearsenalexpansion/config.cpp
Fixes the warning on startup.
Fixes the startup error.
=> fix(opaex): Remove unused display

addons/arsenal/functions/fnc_confirmMigrate.sqf, addons/arsenal/functions/fnc_onClickMigrate.sqf, addons/arsenal/functions/fnc_onLoadoutsDisplayOpened.sqf, addons/arsenal/functions/fnc_onLoadoutsListFilled.sqf, addons/arsenal/functions/fnc_onSelChangedLoadouts.sqf, addons/common/Cfg3DEN.inc, addons/common/config.cpp, addons/resupply/Cfg3DEN.inc, addons/resupply/XEH_PREP.inc.sqf, addons/resupply/XEH_postInit.sqf, addons/resupply/config.cpp, addons/resupply/functions/fnc_addRestockAction.sqf, addons/resupply/functions/fnc_canRestock.sqf, addons/resupply/functions/fnc_consumeRestock.sqf, addons/resupply/functions/fnc_setLimitPerPerson.sqf, addons/resupply/functions/fnc_setLimitTotal.sqf, addons/resupply/functions/fnc_setRestockAmount.sqf, addons/tfar/functions/fnc_saveRadios.sqf
Adds an attribute in the 3DEN editor for using the SWS restock module.
=> feat(resupply): Add restock attribute for 3DEN editor

addons/patches/optre_corvette/CfgVehicles.inc, addons/patches/optre_corvette/config.cpp, addons/patches/optre_corvette/script_component.hpp
Patch corvette door to wait 30 seconds instead of 5 before closing.
=> fix(optre_corvette): Door Timing Increase

.hemtt/lints.toml, .hemtt/project.toml, addons/acre/api/fnc_setRadioOnOffState.sqf, addons/acre/functions/fnc_deserializeRadio.sqf, addons/acre/functions/fnc_onRespawn.sqf, addons/acre/functions/fnc_restoreRadios.sqf, addons/acre/functions/fnc_serializeRadio.sqf, addons/arsenal/XEH_postInit.sqf, addons/arsenal/functions/fnc_confirmMigrate.sqf, addons/cbrn_scripts/functions/fnc_addChemicalHandler.sqf, addons/common/fnc_isInVehicle.sqf, addons/common/functions/fnc_identifyTypes.sqf, addons/medical/functions/fnc_canBandageAndEffective.sqf, addons/modules/functions/fnc_moduleRespawnLoop.sqf, addons/modules/functions/fnc_moduleRespawnPosition.sqf, addons/resupply/functions/fnc_setLimitPerPerson.sqf, addons/resupply/functions/fnc_setLimitTotal.sqf, addons/resupply/functions/fnc_spawnAirdropResupply.sqf, addons/units/functions/fnc_aliveOnInit.sqf, addons/vehicle_trenches/functions/fnc_addBuildHandler.sqf, addons/vehicle_trenches/functions/fnc_lowerPlow.sqf, addons/vehicle_trenches/functions/fnc_raisePlow.sqf, include/x/cba/addons/main/script_macros_common.hpp
The newest version of HEMTT introduced some additional linting stuff, this addresses those things.
=> fix(hemtt): Fix warnings from hemtt upgrades

addons/medical/ACE_Medical_Treatment.inc
- ACE updated their wound configs to use the term 'Large' instead of 'Major', this reflects it in the Medigel and Biofoam which should fix its effectiveness.
=> fix(medical): Biofoam and medigel less effective in most recent ACE update

addons/optre_compat/CfgVehicles.inc
- Add CBA compatibility to the new OPTRE vehicle event handlers.
=> fix(optre_compat): CBA patch for new OTPRE vic event handlers

.hemtt/project.toml
The project file still listed Fapovo which I removed.
=> chore: Remove Fapovo from the presets

addons/main/script_macros.hpp, addons/units/o_cla/faction.inc, addons/units/o_cla/script_component.hpp
I've gone through and used macros for most of this stuff to make it easier to parse.
Macros effectively just expand to a block of code. The reason the magazines weren't showing up before is because `TransportMagazines` uses `magazine` instead of `name` for the property. MACRO_ADDITEM/MACRO_ADDMAGAZINE has the right properties for each of them.
=> fix(o_cla): Magazines not showing up in backpacks

addons/units/o_ura/CfgVehicles.inc
=> feat(units/o_ura): Re-add masks to URA

addons/patches/pollution/CfgWeapons.inc
- Fixes the popup about no entry for HitpointsProtectionInfo.scope.
=> fix(patches): Added polluted base for HitpointsProtectionInfo

addons/modules/functions/fnc_moduleRespawnPosition.sqf
- Use posASL for water positions and ATL for ground positions, since Arma can't make up its mind on whether it's broken or not.
=> fix(modules): Set unit respawn to the right altitude when over water

addons/gear/aceax_models/XtdGearModels.inc, addons/gear/data/textures/helmet_demon_co.paa, addons/gear/data/textures/helmet_legion_co.paa, addons/gear/data/textures/legs_demon_co.paa, addons/gear/data/textures/legs_legion_co.paa, addons/gear/data/textures/odst_addons_demon_co.paa, addons/gear/data/textures/odst_addons_legion_co.paa, addons/gear/legacy/CfgWeapons.inc, addons/gear/legacy/XtdGearInfos.inc, addons/weapons/sxmr397/CfgMagazines.inc
Originally planned in march of 2024, these textures by Jazz hadn't seen the light of day and I'd like to fix that without waiting any longer. Sought every instance of "demon" and changed to "legion" in textures, arsenal and one weapon description.
=> update: Demon -> Legion name and armor changes
